import React from "react";
import { Gift, History, Star, WalletCards } from 'lucide-react'
import { useEffect, useState } from 'react'
import { getLoyalty, getLoyaltyHistory } from '../../services/loyaltyApi'

export default function Loyalty() {
  const [data, setData] = useState(null)
  const [history, setHistory] = useState([])
  useEffect(() => { Promise.all([getLoyalty(), getLoyaltyHistory()]).then(([loyalty, items]) => { setData(loyalty); setHistory(items) }).catch(() => {}) }, [])
  return <section className="section"><div className="container profile-page"><div className="page-heading"><div><span className="eyebrow">REWARDS</span><h1>Loyalty & Rewards</h1><p>Earn points from completed orders and use them on future purchases.</p></div></div><div className="stats-grid loyalty-stats"><div className="stat-card"><span className="stat-icon"><Star size={19}/></span><span className="eyebrow">AVAILABLE POINTS</span><strong>{data?.points ?? 0}</strong><small>100 points = $1</small></div><div className="stat-card"><span className="stat-icon"><WalletCards size={19}/></span><span className="eyebrow">REWARD VALUE</span><strong>${Number(data?.value || 0).toFixed(2)}</strong><small>Available to redeem</small></div><div className="stat-card"><span className="stat-icon"><Gift size={19}/></span><span className="eyebrow">LIFETIME EARNED</span><strong>{data?.lifetimePoints ?? 0}</strong><small>Points earned from delivered orders</small></div></div><section className="panel"><div className="panel-head"><div><span className="eyebrow">HOW IT WORKS</span><h2>Turn shopping into rewards</h2></div></div><div className="feature-grid loyalty-rules"><div><Star size={20}/><strong>Earn</strong><span>Earn 1 point for each $1 of a delivered order.</span></div><div><WalletCards size={20}/><strong>Redeem</strong><span>Each point is worth $0.01 at checkout.</span></div><div><Gift size={20}/><strong>Limit</strong><span>Rewards can cover up to {data?.maxPercent ?? 50}% of an order subtotal.</span></div></div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">REWARD HISTORY</span><h2>Recent activity</h2></div><History size={19}/></div><div className="activity-list">{history.map((item) => <div key={item.id}><span className="activity-avatar"><Gift size={16}/></span><div><strong>{item.orderNumber}</strong><small>{new Date(item.createdAt).toLocaleString()} · {item.status}</small></div><span>{item.earned ? `+${item.earned}` : `-${item.redeemed}`} points</span></div>)}{!history.length && <div className="empty-profile">No loyalty activity yet. Complete a purchase to start earning points.</div>}</div></section></div></section>
}
