import React from "react";
import { Check, Copy, Gift, Mail, MessageCircle, Share2, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { getReferrals } from '../../services/referralApi'

export default function Referrals() {
  const [data, setData] = useState(null)
  const [copied, setCopied] = useState(false)
  const [shared, setShared] = useState('')
  useEffect(() => { getReferrals().then(setData).catch(() => {}) }, [])
  const link = data?.code ? `${window.location.origin}/register?ref=${data.code}` : ''
  const copy = async () => { if (!link) return; await navigator.clipboard.writeText(link); setCopied(true); setTimeout(() => setCopied(false), 1800) }
  const nativeShare = async () => { if (!link) return; if (navigator.share) await navigator.share({ title: 'Join Spark Commerce', text: `Join Spark Commerce with my referral link and get ${data.bonusPoints} reward points after your first delivered order.`, url: link }); else await copy() }
  const whatsapp = () => { window.open(`https://wa.me/?text=${encodeURIComponent(`Join Spark Commerce and get ${data.bonusPoints} reward points after your first delivered order: ${link}`)}`, '_blank') }
  const email = () => { window.location.href = `mailto:?subject=${encodeURIComponent('Join Spark Commerce')}&body=${encodeURIComponent(`Join Spark Commerce with my referral link: ${link}`)}` }
  return <section className="section"><div className="container profile-page"><div className="page-heading"><div><span className="eyebrow">REFER & EARN</span><h1>Invite friends. Earn rewards.</h1><p>Share your referral link. When a new customer completes their first delivered order, both of you receive {data?.bonusPoints ?? 500} loyalty points.</p></div></div><div className="stats-grid loyalty-stats"><div className="stat-card"><span className="stat-icon"><Gift size={19}/></span><span className="eyebrow">YOUR BONUS</span><strong>{data?.bonusPoints ?? 500}</strong><small>Points for each successful referral</small></div><div className="stat-card"><span className="stat-icon"><Users size={19}/></span><span className="eyebrow">SUCCESSFUL REFERRALS</span><strong>{data?.completed ?? 0}</strong><small>Friends who completed an order</small></div><div className="stat-card"><span className="stat-icon"><Share2 size={19}/></span><span className="eyebrow">YOUR CODE</span><strong>{data?.code || '—'}</strong><small>Share this code or your link</small></div></div><section className="panel referral-share"><div className="panel-head"><div><span className="eyebrow">YOUR REFERRAL LINK</span><h2>Share your invite</h2></div><Share2 size={19}/></div><div className="referral-link-box"><input value={link} readOnly /><button className="btn btn-primary" onClick={copy}>{copied ? <><Check size={16}/>Copied</> : <><Copy size={16}/>Copy link</>}</button></div><div className="share-actions"><button className="btn btn-secondary" onClick={nativeShare}><Share2 size={16}/>Share</button><button className="btn btn-secondary" onClick={whatsapp}><MessageCircle size={16}/>WhatsApp</button><button className="btn btn-secondary" onClick={email}><Mail size={16}/>Email</button></div>{shared && <div className="profile-notice success">{shared}</div>}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">REFERRAL HISTORY</span><h2>Your invitations</h2></div></div><div className="activity-list">{(data?.sent || []).map((item) => <div key={item._id}><span className="activity-avatar"><Users size={16}/></span><div><strong>{item.referredUser?.name || 'Customer'}</strong><small>{item.referredUser?.email || ''} · {new Date(item.createdAt).toLocaleDateString()}</small></div><span className={`status-pill ${item.status === 'completed' ? 'success' : ''}`}>{item.status}</span></div>)}{!data?.sent?.length && <div className="empty-profile">No referrals yet. Share your link to invite your first friend.</div>}</div></section></div></section>
}
